name: Analyze Code
on: [push]
jobs:
  analyze-code:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.15.0
      - run: npm ci
      - run: npm run prettier:check
