name: Analyze Code
on: [push]
jobs:
  run-tests:
    runs-on: ubuntu-20.04
    name: On Node.js v${{ matrix.node }}
    strategy:
      matrix:
        node: ['16', '18']
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - run: npm ci
      - run: npm run prettier:check
