name: Do Various Things After Pushing To Main
on:
  push:
    branches:
      - 'no_push_image'
jobs:
  save-ci-image:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
      -
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: kjirou/sgrb:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - run: docker image ls
