name: Run Tests
on: [push]
jobs:
  run-tests:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - run: docker pull kjirou/sgr_ci
      - run: docker tag kjirou/sgr_ci sgr_ci
      -
        run: make docker/ci/build
      -
        run: docker image ls
      -
        run: make docker/ci/test
