name: Run Tests
on: [push]
jobs:
  run-tests:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        uses: docker/build-push-action@v3
        with:
          load: true
          tags: sgrb:latest
          cache-from: type=gha
      - run: docker tag sgrb sgr_ci
      - run: docker image ls
      - run: make docker/ci/test
