name: Run tests
on: [push]
jobs:
  run-tests:
    runs-on: ubuntu-20.04
    name: Run tests on Node.js v${{ matrix.node }}
    strategy:
      matrix:
        node: [ '16', '18' ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - run: npm ci
      - run: npm run test:ci -- --verbose
