name: Test Build And Push Docker Images

on:
  push:
    branches:
      - 'test_build_and_push_docker_images'
      #- 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        run: make docker/local/build
      -
        run: docker image ls
      -
        run: docker tag sgr_local:latest kjirou/sgr_ci_test
      -
        name: Push docker image
        run: docker push kjirou/sgr_ci_test:latest
